# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-11-18 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('school', models.CharField(max_length=100)),
                ('studentnumber', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('gradeid', models.IntegerField()),
                ('userlogin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.UserLogin')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('userlogin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.UserLogin')),
            ],
        ),
    ]
