# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-11-21 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_delete_userlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitorinfo',
            name='gradeid',
        ),
        migrations.AlterField(
            model_name='competitorinfo',
            name='studentnumber',
            field=models.CharField(max_length=100),
        ),
    ]
