# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-26 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('register', '0003_auto_20181122_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('userlogin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.UserLogin')),
            ],
        ),
    ]
