# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-12-26 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20181122_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerinfo',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
