# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-12-26 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_organizerinfo_is_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizerinfo',
            name='is_authenticated',
        ),
        migrations.AddField(
            model_name='organizerinfo',
            name='authenticationstatus',
            field=models.IntegerField(default=0),
        ),
    ]
