# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-11-24 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('file', models.ManyToManyField(to='upload.File')),
            ],
        ),
        migrations.CreateModel(
            name='RootCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1000)),
                ('totalStageNum', models.IntegerField()),
            ],
        ),
    ]
