# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-22 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20181122_0725'),
        ('competition', '0002_auto_20181122_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootcompetition',
            name='members',
            field=models.ManyToManyField(to='register.CompetitorInfo'),
        ),
    ]
