# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-22 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_rootcompetition_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootcompetition',
            name='members',
            field=models.ManyToManyField(to='login.UserLogin'),
        ),
    ]
