# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-23 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_auto_20181222_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootcompetition',
            name='members',
            field=models.ManyToManyField(related_name='competitor', to='login.UserLogin'),
        ),
        migrations.AlterField(
            model_name='rootcompetition',
            name='organizer',
            field=models.ManyToManyField(related_name='organizer', to='login.UserLogin'),
        ),
    ]
