# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-25 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('competition', '0005_auto_20181223_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='login.UserLogin')),
                ('members', models.ManyToManyField(related_name='member', to='login.UserLogin')),
            ],
        ),
        migrations.AlterField(
            model_name='rootcompetition',
            name='members',
            field=models.ManyToManyField(related_name='cuser', to='login.UserLogin'),
        ),
        migrations.AlterField(
            model_name='rootcompetition',
            name='organizer',
            field=models.ManyToManyField(related_name='ouser', to='login.UserLogin'),
        ),
    ]
