# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-26 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_auto_20181225_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootcompetition',
            name='maxmember',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
