# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-26 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('competition', '0007_rootcompetition_maxmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='team',
            name='member',
            field=models.ManyToManyField(related_name='member', to='login.UserLogin'),
        ),
    ]
