# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-26 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_auto_20181226_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='member',
            new_name='members',
        ),
    ]
