# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-26 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0010_team_competition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='competition',
            new_name='compe_id',
        ),
    ]
