# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-26 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0011_auto_20181226_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='compe_id',
            new_name='comp_id',
        ),
        migrations.AlterField(
            model_name='rootcompetition',
            name='maxmember',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rootcompetition',
            name='totalStageNum',
            field=models.IntegerField(default=1),
        ),
    ]
