# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-26 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0012_auto_20181226_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='comp_id',
        ),
        migrations.AddField(
            model_name='team',
            name='comp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='competition.RootCompetition'),
        ),
    ]
