# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-26 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0013_auto_20181226_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rootcompetition',
            name='img',
        ),
        migrations.AddField(
            model_name='rootcompetition',
            name='imgurl',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='comp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp', to='competition.RootCompetition'),
        ),
    ]
