# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-26 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('competition', '0015_auto_20181227_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rootcompetition',
            name='organizer',
        ),
        migrations.AddField(
            model_name='rootcompetition',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.UserLogin'),
        ),
    ]
