# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-27 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0017_auto_20181227_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootcompetition',
            name='judge',
            field=models.ManyToManyField(related_name='juser', to='login.UserLogin'),
        ),
    ]
