# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-27 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
        ('competition', '0018_auto_20181227_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootcompetition',
            name='file',
            field=models.ManyToManyField(related_name='upload_file', to='upload.File'),
        ),
        migrations.AlterField(
            model_name='rootcompetition',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img', to='upload.File'),
        ),
    ]
