# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-27 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0019_auto_20181227_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootcompetition',
            name='file',
            field=models.ManyToManyField(related_name='uploadfile', to='upload.File'),
        ),
    ]
