# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-12-27 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
